services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:v2.5.6
    container_name: immich-server
    ports:
      - 2283:2283
    volumes:
      - /opt/docker/immich/upload:/usr/src/app/upload
    environment:
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      REDIS_HOSTNAME: ${REDIS_HOSTNAME}
      IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning:3003
    depends_on:
      - redis
      - database
    restart: unless-stopped
    networks:
      - immich-network

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v2.5.6
    container_name: immich-machine-learning
    volumes:
      - /opt/docker/immich/cache:/cache
    environment:
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      REDIS_HOSTNAME: ${REDIS_HOSTNAME}
    restart: always
    networks:
      - immich-network

  redis:
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    container_name: redis
    restart: always
    networks:
      - immich-network

  database:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - immich_postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - immich-network

networks:
  immich-network:
    driver: bridge

volumes:
  immich_postgres:
    driver: local